import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";
import styles from "../styles/Page.module.scss";

export default function Page(
	props: React.PropsWithChildren<{
		title: string;
	}>
) {
	return (
		<>
			<Head>
				<title>{props.title ? props.title : "JRPianoTuning"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Alegreya+Sans:wght@700&family=Open+Sans&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<Header></Header>

			<main className={styles.main}>{props.children}</main>

			<Footer></Footer>
		</>
	);
}
